### PR TITLE
Fix/geoarrow impl

### PR DESCRIPTION
**Pull request by guidorice**
- Implement a memory layout which is informed and inspired by GeoArrow. 
- Add geoarrow-python to conda dependencies, for future interop (import/export of geoarrow features).

### CODE REVIEW

**Comment by kylebarron** [comment]
I don't know much about mojo but it should be possible to interoperate with the c-based geoarrow work @paleolimbot is working on in https://github.com/geoarrow/geoarrow-c and https://github.com/geoarrow/geoarrow-python, and my rust-based WIP python bindings in https://github.com/geoarrow/geoarrow-rs, in case that's of use to you at all

**Comment by guidorice** [comment]
Hey @kylebarron 👋🏽 thanks for stopping by. I was just looking at `geoarrow-python` today, and noticed you were a dev on it! 😄  Mojo has great Python interop, and so I do plan to support import/export from the geoarrow format, using Mojo -> Python -> `geoarrow-python`. 

For the internals of the current mojo package, I am leaning towards a more geo-arrow "inspired" memory layout, rather than direct interop with the C  or Python library. To get an idea of what I mean, there this struct:
https://github.com/guidorice/geo-features/blob/ca1723cdd84173afba4bf6a5c0bf1852fe74ed5a/geo_features/geom/layout.mojo

It's early days- none of this is really usable yet though.

**Comment by guidorice** [comment]
Also, Mojo's C ABI interop does not exist yet, but I am guessing it will be great when it lands.

**Comment by kylebarron** [comment]
Obviously I'm biased, but I'd encourage you to adopt the same memory layout as GeoArrow. My premise is that memory-layout conversions between programs in the same or adjacent memory spaces is a bottleneck (it looks like [you've hit this too](https://github.com/guidorice/devblog/blob/master/src/pages/points-within-polygons/index.md#serialize-all-the-things)), and that GeoArrow has the potential to speed up interop by being zero-copy between programs written in many different languages (mojo, python, c, rust). Ideally, if mojo-based apps are using a geoarrow-based layout, they'll get the benefit of free interfacing with other python libraries using GeoArrow, [like a map visualization package I'm working on](https://developmentseed.org/blog/2023-10-23-lonboard).

> To get an idea of what I mean, there this [struct `Layout`](https://github.com/guidorice/geo-features/blob/0fda52ac4690f9cc7829e6cd87bb190d3b5ee10a/geo_features/geom/layout.mojo)

If, for a polygon array, you have:

- a flat array of coordinates
- offsets into the coords where each ring starts
- offsets into the above offsets where each polygon starts
- offsets into the above offsets where each MultiPolygon starts

That's the same as the geoarrow memory layout already. I don't see anything at a glance that's different

**Comment by guidorice** [comment]
@kylebarron @paleolimbot cool, thanks for the feedback- here are some more thoughts and answers. Thanks for the Lon-board link, sorry I have yet to read through the blog post and look at it in detail. I am somewhat familiar with deck.gl, having worked with it a bit in the past. That was rather a failure because probably because I don't know WebGL though. :) 

> You can use Python tools like geoarrow-c to handle exporting to something like the Arrow C Data interface if that's something you'd like to do.

Exactly! Definitely want to be able import/export efficiently, but without limiting future developments on the Mojo side. 

>  It seems like the primary motivation here is interop with Python

Mojo will eventually be a general purpose language with many use cases that do not interop with Python packages at all. Calling Python from Mojo is a bonus, and a productivity boost because we are able to build upon the Python ecosystem to fill in the gaps in Mojo right now- and there are many gaps and sharp edges. btw we cannot call Mojo from Python, although that seems possible it will change in future.

One of the main use cases for Mojo is moving compute-bound things out of Python, and running it closer to the hardware with vectorization and concurrency, and more control over memory layouts and things.

> That's the same as the geoarrow memory layout already. I don't see anything at a glance that's different.

One main difference: if I am reading the geoarrow spec correctly, it always expects float64 (double) arrays for geometries. Please correct me if I am mis-reading that. I am guessing this is because historically, Javascript's number type and Python's float type are both 64-bits, so it was kind of adopted as an interchange format.

In Mojo, and other systems languages such as Zig, there is quite of control over bit width of numeric types, and we can even create new low level types that are register-passable, or arbitrary bit width numeric types. Mojo is oriented towards heterogeneous compute (think everything from tiny embedded systems to laptops to compute clusters). 

Here are some use cases:

- In game engines, float32 is commonly used as for balance between memory usage and precision.
- Several geographic projections (UTM for ex) use unsigned values, so in some of them an unsigned int32 would fit all possible values.
- float32 has 7 decimal digits of precision, sufficient for many geospatial applications.
- For ML applications, it's possible a float16 or some more obscure floating point formats would be required.
- In Mojo, a core feature is vectorization with SIMD, and here we generally want to choose the smallest data type possible, to fit as many of them at once into a vector registers.

just a few links if you are curious.

https://docs.modular.com/mojo/stdlib/builtin/simd.html
https://cloud.google.com/blog/products/ai-machine-learning/bfloat16-the-secret-to-high-performance-on-cloud-tpus
https://ironrust.substack.com/p/custom-bitwidth-integers-a-case-for
https://docs.modular.com/mojo/programming-manual.html#autotuning-adaptive-compilation

My current thinking is a it's a balance and trade-off between supporting Mojo's parametric types for numerical computing, but also making interchange with geo-arrow efficient (but not necessarily zero-copy).

**Comment by kylebarron** [comment]
> it always expects float64 (double) arrays for geometries. Please correct me if I am mis-reading that. I am guessing this is because historically, Javascript's number type and Python's float type are both 64-bits, so it was kind of adopted as an interchange format.

In my view, it also makes most sense to start with f64 types because it's not ideal for the _library_ to put constraints on the end user of the maximum precision they can use. As an example, deck.gl put in a ton of effort to emulate f64 precision on the GPU because with f32s the position of a coordinate would "jitter" when zooming in on the point in a map. For many applications, f32 precision is enough, but there exist some where it isn't.

I absolutely agree that geoarrow should _allow_ f32 types, even if some libraries will only work with f64 internally. (In particular, for my geoarrow-rs Rust work, all georust algorithms I'm binding to are [generic over all float types](https://docs.rs/geo/latest/geo/trait.GeoFloat.html), and relevant ones are also [generic over integer types](https://docs.rs/geo/latest/geo/trait.GeoNum.html).)

> a core feature is vectorization with SIMD

Off topic, (and I don't know much about SIMD) but I'm really curious how many geospatial algorithms are amenable to SIMD... It would seem that you'd have to branch on e.g. the number of coordinates per ring.

**Comment by guidorice** [comment]
Yes agreed that defaulting to f64 but also being generic over other numeric types seems like the ideal solution, and would also enable (in future/theory) the zero-copy scenario for geoarrow.

> Off topic, (and I don't know much about SIMD) but I'm really curious how many geospatial algorithms are amenable to SIMD... It would seem that you'd have to branch on e.g. the number of coordinates per ring.

➕ yeah, me too. Mojo makes it straightforward to experiment with this kind of thing. mojo compiler provides some functional tools for binning simd calls.

**Comment by guidorice** [comment]
@paleolimbot @kylebarron - an update and also, much obliged to ask another question for whoever is more experienced with geoarrow format:

Q: In geoarrow, is the validity buffer ever actually used? I understand it's basically a requirement coming from the arrow memory layout. For example all these `from_geobuffers()` methods, which seem like the mechanism via which I could instantiate geo-arrow objects, they all take a validity buffer:

https://github.com/geoarrow/geoarrow-python/blob/ff9771e5745e263bd4100fe796a0031e8f411b67/geoarrow-pyarrow/src/geoarrow/pyarrow/_type.py#L326

My mental model is the validity buffer is used for representing nulls, which we don't have in geographic/geometric features. (We would have nulls, in attributes tables, but that's another issue)

Additionally here are logging a coulple of links, I discovered that another dev has already has done some preliminary work implemented a couple of arrow utility clases in mojo, including a bitmap validity buffer:

https://github.com/modularml/mojo/discussions/118
https://github.com/sa-/arrow.mojo/blob/main/src/arrow.mojo

That said, it's definitely look more overhead than I imagined to conform to the geoarrow memory layout, at least for now the utility of using a ready made Mojo container type (Tensor) is going to outweigh the padding and alignment constraints which arrow buffers adds.

But definitely will revisit this in the future to add geoarrow as an interchange format. Mojo is fast at memcopy and type-casting operations. Its a compromise.

PS by profession, I am mostly a python and javscript dev- so really just getting up to speed on systems programming stuff here!

**Comment by kylebarron** [comment]
Arrow doesn't _require_ the validity buffer per se (if you have no nulls, it doesn't allocate one), but given that it allows for one, it seems reasonable to allow for null geospatial objects. 

In the spec, we allow for [both missing and empty geometries](https://geoarrow.org/format#missing-values-nulls). So for instance, we might get a `Point EMPTY` back from an intersection query, where the operation succeeded but returned with an empty geometry. But in other cases, we might have attribute data where the geometry is fully missing, and I think that's a case where using the validity buffer to represent that makes sense.

I'm not sure if there's been a decision on whether every implementation is required to support a null buffer 🤷‍♂️ 

> using a ready made Mojo container type (Tensor) is going to outweigh the padding and alignment constraints which arrow buffers adds

I don't know mojo, but I wouldn't have guessed there would be padding and alignment differences. Either way, you probably want the buffers aligned on 8-byte offsets for memory access?

> PS by profession, I am mostly a python and javscript dev- so really just getting up to speed on systems programming stuff here!

I think that goes for all of us 🙂

**Pull request merged**
